# Generated by Django 5.0.6 on 2026-06-03 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='fragrancerequest',
            index=models.Index(fields=['status'], name='idx_inquiry_status'),
        ),
        migrations.AddIndex(
            model_name='fragrancerequest',
            index=models.Index(fields=['-created_at'], name='idx_inquiry_created_at'),
        ),
    ]
